### ISSUE TITLE
Morphman doesn't recognize the addon

### ISSUE THREAD

**Issue by postkevone** [Luukuton/MecabUnidic#1]
I am trying to install this addon instead of the outdated version on anki web (https://ankiweb.net/shared/info/13462835)
But morphman doesn't seem to recognize this addon, is there something I am missing?

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.43 (0fbae6bc) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.14.6
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-07-17 11:40:37
Add-ons possibly involved: ⁨morphman⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/kebi/Library/Application Support/Anki2/addons21/morphman/morph/util_external.py", line 38, in __call__
    return self.cache[args]
KeyError: ('電車はたった今出たところです。',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kebi/Library/Application Support/Anki2/addons21/morphman/morph/util_external.py", line 38, in __call__
    return self.cache[args]
KeyError: ('電車はたった今出たところです。',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kebi/Library/Application Support/Anki2/addons21/morphman/morph/util_external.py", line 38, in __call__
    return self.cache[args]
KeyError: ()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kebi/Library/Application Support/Anki2/addons21/morphman/__init__.py", line 17, in onMorphManRecalc
    main.main()
  File "/Users/kebi/Library/Application Support/Anki2/addons21/morphman/morph/main.py", line 581, in main
    allDb = mkAllDb(cur)
  File "/Users/kebi/Library/Application Support/Anki2/addons21/morphman/morph/main.py", line 196, in mkAllDb
    ms = getMorphemes(morphemizer, fieldValue, ts)
  File "/Users/kebi/Library/Application Support/Anki2/addons21/morphman/morph/morphemes.py", line 166, in getMorphemes
    ms = morphemizer.getMorphemesFromExpr(expression)
  File "/Users/kebi/Library/Application Support/Anki2/addons21/morphman/morph/morphemizer.py", line 49, in getMorphemesFromExpr
    morphs = self._getMorphemesFromExpr(expression)
  File "/Users/kebi/Library/Application Support/Anki2/addons21/morphman/morph/morphemizer.py", line 113, in _getMorphemesFromExpr
    return getMorphemesMecab(expression)
  File "/Users/kebi/Library/Application Support/Anki2/addons21/morphman/morph/util_external.py", line 40, in __call__
    value = self.func(*args)
  File "/Users/kebi/Library/Application Support/Anki2/addons21/morphman/morph/mecab_wrapper.py", line 106, in getMorphemesMecab
    ms = [getMorpheme(m.split('\t')) for m in interact(e).split('\r')]
  File "/Users/kebi/Library/Application Support/Anki2/addons21/morphman/morph/util_external.py", line 40, in __call__
    value = self.func(*args)
  File "/Users/kebi/Library/Application Support/Anki2/addons21/morphman/morph/mecab_wrapper.py", line 253, in interact
    p, _ = mecab()
  File "/Users/kebi/Library/Application Support/Anki2/addons21/morphman/morph/util_external.py", line 40, in __call__
    value = self.func(*args)
  File "/Users/kebi/Library/Application Support/Anki2/addons21/morphman/morph/mecab_wrapper.py", line 246, in mecab
    return spawnMecab(m.mecabCmd[:1] + m.mecabCmd[4:], si), mecab_source
  File "/Users/kebi/Library/Application Support/Anki2/addons21/morphman/morph/mecab_wrapper.py", line 141, in spawnMecab
    raise OSError(
OSError: Unexpected MeCab dictionary format; unidic or ipadic required.
Try installing the 'Mecab Unidic' or 'Japanese Support' addons,
or if using your system's `mecab` try installing a package
like `mecab-ipadic`
```

**Comment by postkevone** [comment]
The reason could be that one or more files in the v1.0 release archive is corrupted.

**Comment by CrescentKohana** [comment]
I wasn't able to replicate the Anki error but you're right about the corruption. `support/sys.dic` in the release zip should have the SHA256 of `5f458365549e976ed1e10fd56fab8e9e38ddc7126bb9a6c8c208589a71b1b86d`. 

It's sourced from [UniDic 3.1.0](https://unidic.ninjal.ac.jp/download#unidic_csj).

I released [a new version](https://github.com/Luukuton/MecabUnidic/releases/tag/v1.1) (v1.1) containing correct files (checked multiple times after each step) with SHA256 hashes of every file.

**Comment by postkevone** [comment]
Thank you for your fast response, unfortunately morphman still doesn't recognize the plugin.

I suppose this is a problem related to macOS.

Does this version work with the standard version of morphman, or do you need to make some adjustments to make it work?
I tried this method in the past: https://www.reddit.com/r/LearnJapanese/comments/g8ngtm/how_did_you_guys_update_your_mecab_unidic/

**Comment by CrescentKohana** [comment]
> Does this version work with the standard version of morphman

Yes.

> do you need to make some adjustments to make it work?

No. Just copying the directory inside the zip file to the addons directory and choosing it in MorphMan's settings should suffice. Also make sure to delete the old version of MecabUnidic too.
![image](https://user-images.githubusercontent.com/3739842/126049052-0c0927a2-28b5-4dd1-aa5f-32d5d4dc345a.png)

Also tested with Anki 2.1.35 and 2.1.44 so can't be because of that.

> I suppose this is a problem related to macOS.

Most likely yes. To be more exact, the MeCab files built on Arch Linux probably aren't working on macOS. 

- You could just take UniDic files `char.bin, dicrc matrix.bin, model.bin, sys.dic, unk.dic` from the 1.1 release and copy them to the old ([https://ankiweb.net/shared/info/13462835](https://ankiweb.net/shared/info/13462835)) addon's support directory. This should be enough for the latest language data. MeCab isn't as important anyway so it's probably fine to use the old version of that.
  - If this works for you, I'll release a separate zip file for macOS.
- In the case if you want the latest MeCab (or if above doesn't work), you could try to build it on your system (I can't as I don't have a Mac):
  - Download the source code for MeCab [here](https://drive.google.com/uc?export=download&id=0B4y35FiV1wh7cENtOXlicTFaRUE) (from [https://taku910.github.io/mecab/#download](https://taku910.github.io/mecab/#download))
  - Run the following commands to build it (you'll need g++ 3.4.3 or higher):
  ```
   tar zxfv mecab-X.X.tar.gz
   cd mecab-X.X
   ./configure 
   make
   make check
   su
   make install
   ```
  - After that at least on Linux the binary was located in /usr/local/bin/mecab and the shared object file in /usr/local/lib/libmecab.so.2 (the libmecab is probably called libmecab.2.dylib on macOS.)
  - If this works for you, send me the files you built and I'll release a separate zip file for macOS.

**Comment by postkevone** [comment]
Thank you very much, your instructions worked perfectly!
The unidic files worked fine from the start.
I compiled mecab on my mac and copied the /bin/, /etc/, /include/, /lib/ files into the directory and morphan was working without any problems.

I attach the mecab folder compiled on macos.

[mecab-0.996_macos.zip](https://github.com/Luukuton/MecabUnidic/files/6835329/mecab-0.996_macos.zip)

**Comment by CrescentKohana** [comment]
Great to hear, and thanks a lot for the files!

**Comment by CrescentKohana** [comment]
Released [a new version](https://github.com/Luukuton/MecabUnidic/releases/tag/v1.2) (1.2) with separate releases for each OS. Thanks again for the binaries.
